### ISSUE TITLE
Snap floating tiddlers to left, right, top and bottom

### ISSUE THREAD

**Issue by kookma** [admls/Mentat#15]
Is it possible to have a snap button or by drag and drop to snap the floating tiddlers to left, right, button, and top of screen (here, browser window)

Ref:

1. w3.org (https://www.w3.org/TR/css-scroll-snap-1/)
1. https://answers.microsoft.com/en-us/windows/forum/windows_10-start/show-windows-side-by-side-in-windows-10/4d437298-310f-4429-9297-328406a2e941
1.  https://www.nurgo-software.com/products/aquasnap
1. https://css-tricks.com/introducing-css-scroll-snap-points/

**Comment by admls** [comment]
This should be coming soon. One of the changes I made to volant was to add a handful of hooks. I should be able to hook in fairly easily. I suspect that I'll be able to get a simple version of this add-on put together and released next week. Greater configurability will probably come a little later. But look out for this sometime next week!

**Comment by kookma** [comment]
Thanks @admls 
I am available for evaluation and if I can of any help I would be happy to do that!
By the way, as I said before Mentat and specially the Volant plugin takes TW one step forward!
You saw in the forum, many people excited by Volant!

Best
Mohammad

**Comment by admls** [comment]
Hi @kookma,
Check out the Volant-Rapid add-on. This was a great suggestion. I'm loving it even more than I thought I would. I may just add it straight into Volant in the future.

Best wishes,
admls

**Comment by kookma** [comment]
Many thanks!
I just downloaded the latest version and it work amazing!

Thank you again!
Mohammad
