### ISSUE TITLE
Create Tiddlers using script in an active window

### ISSUE THREAD

**Issue by kookma** [admls/Mentat#21]
Assume you have an active window, create a tiddler with the below contents

<$button>
<$action-createtiddler $basetitle="Test" />
Create a Tiddler
</$button>

This will create the new tiddler in the default story river not in the active window!

**Comment by admls** [comment]
Hi Mohammad,

I'm unable to reproduce this issue. Action-createtiddler doesn't automatically add the tiddler to the story river. Could you give me some more details on what's going on? This shouldn't be able to happen,

Even if I explicitly add the tiddler to the $:/StoryList with this:

```
<$button>
<$action-createtiddler $basetitle="Test" $savetitle="$:/state/temp/title" />
<$action-listops $tiddler="$:/StoryList" $subfilter=" +[insertbefore{$:/state/temp/title}]" />
Create a Tiddler
</$button>
```

It is still adding it to the window and not the default story river for me.

**Comment by kookma** [comment]
Hi admls,
 Sorry, it was my mistake!
The tiddlers are created in the active window!
